<?php

use Illuminate\Database\Seeder;

class gamesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('games')->insert([

        	// POOL 1
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "5",
                'score_team2' => "2",
                'teams1_id' => "1",
                'teams2_id' => "2",
                'pools_id' => "1",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "3",
                'teams2_id' => "4",
                'pools_id' => "1",
                'courts_id' => "2",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "1",
                'teams1_id' => "2",
                'teams2_id' => "3",
                'pools_id' => "1",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "1",
                'teams2_id' => "4",
                'pools_id' => "1",
                'courts_id' => "2",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "1",
                'teams2_id' => "3",
                'pools_id' => "1",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "2",
                'teams2_id' => "4",
                'pools_id' => "1",
                'courts_id' => "2",
            ],
            
            // POOL 2
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "5",
                'teams2_id' => "6",
                'pools_id' => "2",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "7",
                'teams2_id' => "8",
                'pools_id' => "2",
                'courts_id' => "4",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "6",
                'teams2_id' => "7",
                'pools_id' => "2",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "5",
                'teams2_id' => "8",
                'pools_id' => "2",
                'courts_id' => "4",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "5",
                'teams2_id' => "7",
                'pools_id' => "2",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "6",
                'teams2_id' => "8",
                'pools_id' => "2",
                'courts_id' => "4",
            ],

            // POOL 3
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "9",
                'teams2_id' => "10",
                'pools_id' => "3",
                'courts_id' => "5",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "11",
                'teams2_id' => "12",
                'pools_id' => "3",
                'courts_id' => "6",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "10",
                'teams2_id' => "11",
                'pools_id' => "3",
                'courts_id' => "5",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "9",
                'teams2_id' => "12",
                'pools_id' => "3",
                'courts_id' => "6",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "9",
                'teams2_id' => "11",
                'pools_id' => "3",
                'courts_id' => "5",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "10",
                'teams2_id' => "12",
                'pools_id' => "3",
                'courts_id' => "6",
            ],

            // POOL 4
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "13",
                'teams2_id' => "14",
                'pools_id' => "4",
                'courts_id' => "7",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "15",
                'teams2_id' => "16",
                'pools_id' => "4",
                'courts_id' => "8",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "14",
                'teams2_id' => "15",
                'pools_id' => "4",
                'courts_id' => "7",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "13",
                'teams2_id' => "16",
                'pools_id' => "4",
                'courts_id' => "8",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "13",
                'teams2_id' => "15",
                'pools_id' => "4",
                'courts_id' => "7",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "14",
                'teams2_id' => "16",
                'pools_id' => "4",
                'courts_id' => "8",
            ],

			// POOL 5
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "17",
                'teams2_id' => "18",
                'pools_id' => "5",
                'courts_id' => "9",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "19",
                'teams2_id' => "20",
                'pools_id' => "5",
                'courts_id' => "10",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "18",
                'teams2_id' => "19",
                'pools_id' => "5",
                'courts_id' => "9",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "17",
                'teams2_id' => "20",
                'pools_id' => "5",
                'courts_id' => "10",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "17",
                'teams2_id' => "19",
                'pools_id' => "5",
                'courts_id' => "9",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "18",
                'teams2_id' => "20",
                'pools_id' => "5",
                'courts_id' => "10",
            ],

            // POOL 6
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "21",
                'teams2_id' => "22",
                'pools_id' => "6",
                'courts_id' => "11",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "23",
                'teams2_id' => "24",
                'pools_id' => "6",
                'courts_id' => "12",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "22",
                'teams2_id' => "23",
                'pools_id' => "6",
                'courts_id' => "11",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "21",
                'teams2_id' => "24",
                'pools_id' => "6",
                'courts_id' => "12",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "21",
                'teams2_id' => "23",
                'pools_id' => "6",
                'courts_id' => "11",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "22",
                'teams2_id' => "24",
                'pools_id' => "6",
                'courts_id' => "12",
            ],

            // POOL 7
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "25",
                'teams2_id' => "26",
                'pools_id' => "7",
                'courts_id' => "13",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "27",
                'teams2_id' => "28",
                'pools_id' => "7",
                'courts_id' => "14",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "26",
                'teams2_id' => "27",
                'pools_id' => "7",
                'courts_id' => "13",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "25",
                'teams2_id' => "28",
                'pools_id' => "7",
                'courts_id' => "14",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "25",
                'teams2_id' => "27",
                'pools_id' => "7",
                'courts_id' => "13",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "26",
                'teams2_id' => "28",
                'pools_id' => "7",
                'courts_id' => "14",
            ],

            // POOL 8
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "29",
                'teams2_id' => "30",
                'pools_id' => "8",
                'courts_id' => "15",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "31",
                'teams2_id' => "32",
                'pools_id' => "8",
                'courts_id' => "16",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "30",
                'teams2_id' => "31",
                'pools_id' => "8",
                'courts_id' => "15",
            ],
            [
                'date' => "20061223",
                'start_time' => "08:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "29",
                'teams2_id' => "32",
                'pools_id' => "8",
                'courts_id' => "16",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "29",
                'teams2_id' => "31",
                'pools_id' => "8",
                'courts_id' => "15",
            ],
            [
                'date' => "20061223",
                'start_time' => "09:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "30",
                'teams2_id' => "32",
                'pools_id' => "8",
                'courts_id' => "16",
            ],

            // --------------------------- WINNER
             
            // POOL 9
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "1",
                'teams2_id' => "2",
                'pools_id' => "9",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "5",
                'teams2_id' => "6",
                'pools_id' => "9",
                'courts_id' => "2",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "2",
                'teams2_id' => "5",
                'pools_id' => "9",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "1",
                'teams2_id' => "6",
                'pools_id' => "9",
                'courts_id' => "2",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "1",
                'teams2_id' => "5",
                'pools_id' => "9",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "2",
                'teams2_id' => "6",
                'pools_id' => "9",
                'courts_id' => "2",
            ],

            // POOL 10
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "9",
                'teams2_id' => "10",
                'pools_id' => "10",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "13",
                'teams2_id' => "14",
                'pools_id' => "10",
                'courts_id' => "4",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "10",
                'teams2_id' => "13",
                'pools_id' => "10",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "9",
                'teams2_id' => "14",
                'pools_id' => "10",
                'courts_id' => "4",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "9",
                'teams2_id' => "13",
                'pools_id' => "10",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "10",
                'teams2_id' => "14",
                'pools_id' => "10",
                'courts_id' => "4",
            ],

            // POOL 11
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "17",
                'teams2_id' => "18",
                'pools_id' => "11",
                'courts_id' => "5",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "21",
                'teams2_id' => "22",
                'pools_id' => "11",
                'courts_id' => "6",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "18",
                'teams2_id' => "21",
                'pools_id' => "11",
                'courts_id' => "5",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "17",
                'teams2_id' => "22",
                'pools_id' => "11",
                'courts_id' => "6",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "17",
                'teams2_id' => "21",
                'pools_id' => "11",
                'courts_id' => "5",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "18",
                'teams2_id' => "22",
                'pools_id' => "11",
                'courts_id' => "6",
            ],

            // POOL 12
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "25",
                'teams2_id' => "26",
                'pools_id' => "12",
                'courts_id' => "7",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "29",
                'teams2_id' => "30",
                'pools_id' => "12",
                'courts_id' => "8",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "26",
                'teams2_id' => "29",
                'pools_id' => "12",
                'courts_id' => "7",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "25",
                'teams2_id' => "30",
                'pools_id' => "12",
                'courts_id' => "8",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "25",
                'teams2_id' => "29",
                'pools_id' => "12",
                'courts_id' => "7",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "26",
                'teams2_id' => "30",
                'pools_id' => "12",
                'courts_id' => "8",
            ],


            // --------------------------- LOOSER
             
            // POOL 13
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "3",
                'teams2_id' => "4",
                'pools_id' => "13",
                'courts_id' => "9",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "7",
                'teams2_id' => "8",
                'pools_id' => "13",
                'courts_id' => "10",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "4",
                'teams2_id' => "7",
                'pools_id' => "13",
                'courts_id' => "9",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "3",
                'teams2_id' => "8",
                'pools_id' => "13",
                'courts_id' => "10",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "3",
                'teams2_id' => "7",
                'pools_id' => "13",
                'courts_id' => "9",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "4",
                'teams2_id' => "8",
                'pools_id' => "13",
                'courts_id' => "10",
            ],

            // POOL 14
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "11",
                'teams2_id' => "12",
                'pools_id' => "14",
                'courts_id' => "11",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "15",
                'teams2_id' => "16",
                'pools_id' => "14",
                'courts_id' => "12",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "12",
                'teams2_id' => "15",
                'pools_id' => "14",
                'courts_id' => "11",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "11",
                'teams2_id' => "16",
                'pools_id' => "14",
                'courts_id' => "12",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "11",
                'teams2_id' => "15",
                'pools_id' => "14",
                'courts_id' => "11",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "12",
                'teams2_id' => "16",
                'pools_id' => "14",
                'courts_id' => "12",
            ],

            // POOL 15
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "19",
                'teams2_id' => "20",
                'pools_id' => "15",
                'courts_id' => "13",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "23",
                'teams2_id' => "24",
                'pools_id' => "15",
                'courts_id' => "14",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "20",
                'teams2_id' => "23",
                'pools_id' => "15",
                'courts_id' => "13",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "19",
                'teams2_id' => "24",
                'pools_id' => "15",
                'courts_id' => "14",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "19",
                'teams2_id' => "23",
                'pools_id' => "15",
                'courts_id' => "13",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "20",
                'teams2_id' => "24",
                'pools_id' => "15",
                'courts_id' => "14",
            ],

			// POOL 16
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "27",
                'teams2_id' => "28",
                'pools_id' => "16",
                'courts_id' => "15",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "31",
                'teams2_id' => "32",
                'pools_id' => "16",
                'courts_id' => "16",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "28",
                'teams2_id' => "31",
                'pools_id' => "16",
                'courts_id' => "15",
            ],
            [
                'date' => "20061223",
                'start_time' => "10:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "27",
                'teams2_id' => "32",
                'pools_id' => "16",
                'courts_id' => "16",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "27",
                'teams2_id' => "31",
                'pools_id' => "16",
                'courts_id' => "15",
            ],
            [
                'date' => "20061223",
                'start_time' => "11:00:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "28",
                'teams2_id' => "32",
                'pools_id' => "16",
                'courts_id' => "16",
            ],


            // --------------------------- DEMI-FINALE 
             
            // POOL 17
            [
                'date' => "20061223",
                'start_time' => "13:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "1",
                'teams2_id' => "2",
                'pools_id' => "17",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "13:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "9",
                'teams2_id' => "10",
                'pools_id' => "17",
                'courts_id' => "2",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:00:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "2",
                'teams2_id' => "9",
                'pools_id' => "17",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "1",
                'teams2_id' => "10",
                'pools_id' => "17",
                'courts_id' => "2",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "1",
                'teams2_id' => "9",
                'pools_id' => "17",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:30:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "2",
                'teams2_id' => "10",
                'pools_id' => "17",
                'courts_id' => "2",
            ],

            // POOL 18
            [
                'date' => "20061223",
                'start_time' => "13:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "17",
                'teams2_id' => "18",
                'pools_id' => "18",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "13:30:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "1",
                'teams1_id' => "25",
                'teams2_id' => "26",
                'pools_id' => "18",
                'courts_id' => "4",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:00:00",
                'type' => "Simple",
                'score_team1' => "4",
                'score_team2' => "3",
                'teams1_id' => "18",
                'teams2_id' => "25",
                'pools_id' => "18",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:00:00",
                'type' => "Simple",
                'score_team1' => "1",
                'score_team2' => "0",
                'teams1_id' => "17",
                'teams2_id' => "26",
                'pools_id' => "18",
                'courts_id' => "4",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "17",
                'teams2_id' => "25",
                'pools_id' => "18",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "14:30:00",
                'type' => "Simple",
                'score_team1' => "2",
                'score_team2' => "1",
                'teams1_id' => "18",
                'teams2_id' => "26",
                'pools_id' => "18",
                'courts_id' => "4",
            ],

            // --------------------------- FINALE (Classement)
            [
                'date' => "20061223",
                'start_time' => "15:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "1",
                'teams2_id' => "17",
                'pools_id' => "9",
                'courts_id' => "1",
            ],
            [
                'date' => "20061223",
                'start_time' => "15:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "2",
                'teams2_id' => "18",
                'pools_id' => "9",
                'courts_id' => "2",
            ],
            [
                'date' => "20061223",
                'start_time' => "15:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "9",
                'teams2_id' => "25",
                'pools_id' => "9",
                'courts_id' => "3",
            ],
            [
                'date' => "20061223",
                'start_time' => "15:30:00",
                'type' => "Simple",
                'score_team1' => "3",
                'score_team2' => "2",
                'teams1_id' => "10",
                'teams2_id' => "26",
                'pools_id' => "9",
                'courts_id' => "4",
            ]

        ]);
    }
}
